### ISSUE TITLE
Support for the latest changes of the API

### ISSUE THREAD

**Issue by volkanunsal** [tylerpearson/civic_aide#2]
I've been trying to use this gem on [my project](http://www.pollwatchusa.org/), but have been unable to. It breaks in the most unexpected ways, even though all the spec tests are passing. I don't know if that's an API problem or lack of test coverage. Just to give a simple example, I pasted the code in README into my console and got this error:

```
[13] pry(main)> client.election(4100).at('4910 Willet Drive, Annandale, VA 22003')
NoMethodError: undefined method `downcase' for nil:NilClass
from /Users/newuser/.rvm/gems/ruby-2.1.1@pollwatchapi/gems/civic_aide-0.1.1/lib/civic_aide/client.rb:62:in `check_response_status'
```

Note that I am using the latest election id in my call.

This example looks like an issue in the gem, but the v2 of the API looks completely different also, so they may be moving support away from the v1.  Are there any plans to add support for v2 to the gem?

**Comment by tylerpearson** [comment]
Hmm, at this point I actually haven't looked at V2 of the API. Let me see what I can do for updating the code for it.
